server:
  port: 8088
  servlet:
    context-path: /ebook #Tomcat端口
spring:
  application:
    name: springboot-dubbo-ibook
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ibook?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: 335100
      initialSize: 5
      maxActive: 20
      maxWait: 60000

  data:
    mongodb:
      uri: mongodb://localhost:27017/ibook
#      uri: mongodb://zzq:123456@localhost:27017/mydb
#      uri: mongodb://user:pwd@ip1:port1,ip2:port2/database
  thymeleaf:
      cache: false

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO

#dubbo:
#  scan:
#    base-packages: com.ibook.dubbo
#  protocol:
#    name: dubbo
#    port: 20883
#  registry:
##    直连
##    address: N/A
##    address: zookeeper://localhost:20880
## 广播端：使用 multicast 广播注册中心暴露服务地址 (224.0.0.0 - 239.255.255.255)
#    address: multicast://224.5.6.7:20880
